name: Cross-Compile for Windows

on:
  push:
    branches:
      - crystal-flavour
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Cross-compilation)
        run: |
          sudo apt update
          sudo apt install -y mingw-w64
          sudo apt install -y libz-mingw-w64-dev libxml2-mingw-w64-dev libyaml-mingw-w64-dev

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Cross-Compile for Windows (Generate Object Files)
        run: |
          mkdir -p build
          crystal build crystaldump.cr --cross-compile --target x86_64-pc-win32 > build/compile_output.txt
        shell: bash

      - name: Extract Compilation Command
        run: |
          COMPILE_CMD=$(tail -n 1 build/compile_output.txt)
          echo "COMPILE_CMD=$COMPILE_CMD" >> $GITHUB_ENV
        shell: bash

      - name: Link Windows Executable
        run: |
          $COMPILE_CMD -o build/crystaldump.exe
        shell: bash

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: crystaldump-windows
          path: build/crystaldump.exe
