name: Build CrystalDump

on:
  push:
    branches:
      - crystal-flavour
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crystal: [latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Install dependencies
        run: shards install

      - name: Compile CrystalDump (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p build
          crystal build crystaldump.cr --release --static -o build/crystaldump
        shell: bash

      - name: Compile CrystalDump (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          crystal build crystaldump.cr --release -o build/crystaldump.exe

      - name: Upload built executable
        uses: actions/upload-artifact@v3
        with:
          name: crystaldump-${{ runner.os }}
          path: build/crystaldump*
