name: release-windows

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build Windows Executable
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Cross-compilation)
        run: |
          sudo apt update
          sudo apt install -y mingw-w64

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Cross-Compile for Windows
        run: |
          mkdir -p bin
          crystal build crystaldump.cr --release --cross-compile --target x86_64-pc-win32 > bin/compile_output.txt
          LINK_CMD=$(tail -n 1 bin/compile_output.txt)
          eval $LINK_CMD -o bin/CrystalDump.exe
          zip bin/CrystalDump-windows.zip bin/CrystalDump.exe

      - name: Upload Windows executable to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: bin/CrystalDump-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
